resources:
    - type: module
      url: /local/community/custom-header/custom-header.js
    - type: module
      url: /local/community/button-card/button-card.js
    - type: module
      url: /local/community/mini-media-player/mini-media-player-bundle.js
    - type: module
      url: /local/community/lovelace-card-mod/card-mod.js
    - type: js
      url: /local/community/bar-card/bar-card.js
    - type: js
      url: /local/community/vertical-stack-in-card/vertical-stack-in-card.js
    - type: module
      url: /local/community/mini-graph-card/mini-graph-card-bundle.js
    - type: js
      url: /local/community/lovelace-github-entity-row/github-entity-row.js
    - type: module
      url: /local/community/lovelace-auto-entities/auto-entities.js
    - type: module
      url: /local/community/decluttering-card/decluttering-card.js
    - type: module
      url: /local/community/weather-card/weather-card.js
    - type: module
      url: /local/community/simple-weather-card/simple-weather-card-bundle.js
    - type: module
      url: /local/community/lovelace-slider-entity-row/slider-entity-row.js
    - type: module
      url: /local/community/lovelace-fold-entity-row/fold-entity-row.js
    - type: module
      url: /local/community/lovelace-template-entity-row/template-entity-row.js
    - type: js
      url: /local/community/lovelace-card-templater/lovelace-card-templater.js

title: KV53
theme: Backend-selected

custom_header:
    background: rgba(155, 155, 155, 0.25)
    button_text:
        options: '{{ hours24 }}:{{ minutesLZ }} {{ dayNameLong }} {{ dayNum }}. {{ monthNameShort }} {{ year4d }}'

background: var(--background-image)

views:
    - badges:
          - entity: person.eskil_kvalnes
          - entity: person.line_aronsen
          - entity: device_tracker.e_golf
      cards:
          # Lys
          - entities:
                - entities:
                      - light.tradfri_sofa
                      - light.tradfri_blomster
                      - light.tradfri_bokhylle
                  head:
                      entity: light.stuelys
                      name: Stue
                      type: custom:slider-entity-row
                  type: custom:fold-entity-row
                - entities:
                      - light.tradfri_vaskerom
                      - light.tradfri_bodgang
                      - light.tradfri_bod_stor
                      - light.tradfri_bod_liten
                  head:
                      entity: light.boder_og_vaskerom
                      name: Vaskerom
                      type: custom:slider-entity-row
                  type: custom:fold-entity-row
                - entities:
                      - light.tradfri_lekerom
                      - light.lekerompendel
                  head:
                      entity: light.lekerom
                      name: Lekerom
                      type: custom:slider-entity-row
                  type: custom:fold-entity-row
                - light.fibaro_system_fgd212_dimmer_2_level_2
                - light.tradfri_soverom_arya
            show_header_toggle: false
            title: Lys
            type: entities

          # Vær
          - entity: weather.kv53
            name: Vær
            type: custom:simple-weather-card
          
          # Pollenvarsel
          - type: entity-filter
            entities:
            - entity: sensor.pollen_bjork_today
              name: Bjørk
              icon: 'mdi:tree'
            - entity: sensor.pollen_burot_today
              name: Burot
              icon: 'mdi:tree'
            - entity: sensor.pollen_gress_today
              name: Gress
              icon: 'mdi:tree'
            - entity: sensor.pollen_hassel_today
              name: Hassel
              icon: 'mdi:tree'
            - entity: sensor.pollen_or_today
              name: Or
              icon: 'mdi:tree'
            - entity: sensor.pollen_salix_today
              name: Salix
              icon: 'mdi:tree'
            state_filter:
              - operator: '!='
                value: Ingen spredning
            card:
              type: glance
              title: Pollenvarsling
              columns: 3

          # Skallsikring
          - entities:
                - entity: binary_sensor.verandador
                  icon: mdi:lock-outline
                - entity: binary_sensor.soveromsdor
                  icon: mdi:lock-outline
            show_header_toggle: false
            title: Skallsikring
            type: entities

          # Knapper
          - cards:
                - cards:
                      - color: auto
                        color_type: card
                        icon: mdi:weather-sunset-up
                        lock:
                            enabled: true
                        name: God morgen
                        styles:
                            card:
                                - font-size: 12px
                                - font-weight: bold
                                - height: 70px
                        tap_action:
                            action: call-service
                            service: input_boolean.turn_off
                            service_data:
                                entity_id: input_boolean.sleep_mode
                        type: custom:button-card
                      - color: auto
                        color_type: card
                        entity: input_boolean.sleep_mode
                        icon: mdi:weather-night
                        lock:
                            enabled: true
                        name: '[[[ if (entity.state == "on") return "Sovemodus"; else return "God natt" ]]]'
                        styles:
                            card:
                                - font-size: 12px
                                - font-weight: bold
                                - height: 70px
                        tap_action:
                            action: call-service
                            service: script.going_to_sleep
                        type: custom:button-card
                  type: horizontal-stack
                - cards:
                      - color: auto
                        color_type: card
                        icon: mdi:home-map-marker
                        lock:
                            enabled: true
                        name: Ankomst
                        styles:
                            card:
                                - font-size: 12px
                                - font-weight: bold
                                - height: 70px
                        tap_action:
                            action: call-service
                            service: script.turn_off_everything
                        type: custom:button-card
                      - color: auto
                        color_type: card
                        icon: mdi:home-export-outline
                        lock:
                            enabled: true
                        name: Avgang
                        styles:
                            card:
                                - font-size: 12px
                                - font-weight: bold
                                - height: 70px
                        tap_action:
                            action: call-service
                            service: script.turn_off_everything
                        type: custom:button-card
                  type: horizontal-stack
            type: vertical-stack

          # Bevegelse
          - entities:
                - zwave.fibaro_system_fgms001_zw5_motion_sensor
            show_header_toggle: false
            title: Bevegelse
            type: entities

          # Temperatur
          - cards:
                - cards:
                      - color_thresholds_transition: smooth
                        entities:
                            - entity: sensor.fibaro_system_fgms001_zw5_motion_sensor_temperature
                              name: Bodgang
                        font_size: 100
                        group: false
                        hour24: true
                        line_width: 3
                        lower_bound: 0
                        points_per_hour: 1
                        show:
                            extrema: false
                            fill: fade
                            labels: false
                            name: true
                            state: true
                        type: custom:mini-graph-card
                  name: Speedtest
                  type: horizontal-stack
            type: custom:vertical-stack-in-card

          # Media/Chromecast
          - type: entities
            entities:
            - type: custom:mini-media-player
              entity: media_player.plex_anfield
              name: Anfield
              group: true
              source: icon
              icon: mdi:plex
              info: scroll
              artwork: full-cover
              hide:
                controls: true
                volume: true
                power: true
            - type: custom:mini-media-player
              entity: media_player.plex_firefox
              name: Eskil (MBPR)
              group: true
              source: full
              icon: mdi:plex
              info: scroll
              artwork: cover
              hide:
                controls: true
                volume: true
                power: true
            - type: custom:mini-media-player
              entity: media_player.plex_firefox_2
              name: Eskil (Mac Mini)
              group: true
              source: icon
              icon: mdi:plex
              info: scroll
              artwork: cover
              hide:
                controls: true
                volume: true
                power: true
            - type: custom:mini-media-player
              entity: media_player.plex_line_kalstad_sin_ipad
              name: Line (iPad)
              group: true
              source: icon
              icon: mdi:plex
              info: scroll
              artwork: cover
              hide:
                controls: true
                volume: true
                power: true
            - type: custom:mini-media-player
              entity: media_player.lekerom_tv
              group: true
              source: icon
              icon: mdi:cast
              info: scroll
              artwork: cover
              hide:
                controls: true
                volume: true
                power: true
            title: Media
            show_header_toggle: false

          # Strømprisgraf
          - color_thresholds_transition: smooth
            entities:
                - entity: sensor.electricity_price_kveldsolgata_53
                  name: Strømpris
            font_size: 100
            group: false
            hour24: true
            line_width: 3
            lower_bound: 0
            points_per_hour: 1
            show:
                extrema: false
                fill: fade
                labels: false
                name: true
                state: true
            type: custom:mini-graph-card

          # Plexgraf
          - color_thresholds_transition: smooth
            entities:
                - entity: sensor.plex_kv53
                  name: Plex
            font_size: 100
            group: false
            hour24: true
            line_width: 3
            lower_bound: 0
            points_per_hour: 1
            show:
                extrema: false
                fill: fade
                labels: false
                name: true
                state: true
            type: custom:mini-graph-card

          # Kart
          - type: map
            default_zoom: 11
            entities:
              - device_tracker.eskil_iphone_2
              - device_tracker.line_iphone
              - zone.home

          # Søppeltømming
          - title: Renovasjon
            type: entities
            show_header_toggle: false
            entities:
              - type: custom:template-entity-row
                icon: mdi:calendar
                name: "Neste søppeldag"
                state: "{{ states('sensor.next_garbage_pickup_type') }}"
                secondary: "{{ states('sensor.next_garbage_pickup_date') }}"
              - type: custom:template-entity-row
                icon: mdi:trash-can
                name: "Restavfall"
                state: "{{ states('sensor.restavfall_pickup_date') }}"
              - type: custom:template-entity-row
                icon: mdi:newspaper
                name: "Papir"
                state: "{{ states('sensor.papir_pickup_date') }}"

          #START VW CAR IMAGE
          - title: VW e-Golf
            type: picture-elements
            image: /local/egolf.png
            elements:
              #State images to illustrate on top of car
              - type: image
                entity: switch.e_golf_climatisation
                image: /local/blank.png
                style:
                  top: 39.5%
                  left: 55%
                  width: 43%
                state_image:
                  "on": /local/passat_heat.png

              - type: image
                entity: binary_sensor.e_golf_external_power
                image: /local/blank.png
                style:
                  top: 62.8%
                  left: 21.2%
                  width: 43%
                state_image:
                  "on": /local/passatcharging.png

              - type: image
                entity: binary_sensor.e_golf_parking_light
                image: /local/blank.png
                style:
                  top: 66.8%
                  left: 37.2%
                  width: 37%
                state_image:
                  "on": /local/passat_light.png

              - type: image
                entity: lock.e_golf_door_locked
                image: /local/blank.png
                style:
                  top: 42.3%
                  left: 57%
                  width: 2%
                state_image:
                  locked: /local/blink.gif

              # Top left row with state icons
              - type: state-icon
                entity: lock.e_golf_door_locked
                style:
                  top: 87%
                  left: 47%

              - type: state-icon
                entity: switch.e_golf_climatisation
                hold_action: toggle
                style:
                  top: 87%
                  left: 58%

              - type: state-icon
                entity: switch.e_golf_window_heater
                hold_action: toggle
                style:
                  top: 87%
                  left: 69%

              #Top right icons
              - type: state-icon
                entity: switch.e_golf_charging
                style:
                  top: 87%
                  left: 80%

              - type: state-label
                entity: sensor.e_golf_battery_level
                style:
                  top: 96%
                  left: 81%

              - type: state-icon
                entity: sensor.e_golf_charging_time_left
                style:
                  top: 87%
                  left: 91%

              - type: state-label
                entity: sensor.e_golf_charging_time_left
                style:
                  top: 96%
                  left: 92%
          #END VW IMAGE CARD
      path: default_view
